name: Flatpak CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder gnupg

      - name: Setup Flathub
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install SDK
        run: |
          flatpak install --user -y flathub org.freedesktop.Sdk//24.08 org.freedesktop.Platform//24.08

      - name: Build Flatpak
        run: |
          flatpak-builder \
            --force-clean \
            --user \
            --repo=repo \
            build-dir \
            io.github.blacksamdev.Popcorn.json

      - name: Export repo
        run: |
          flatpak build-update-repo repo
